#!/usr/bin/env node
import { Command } from 'commander';
import * as clack from '@clack/prompts';
import * as esbuild from 'esbuild';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';

interface PackOptions {
  name?: string;
  input?: string;
  output?: string;
}

async function getProjectsDir(): Promise<string> {
  return path.join(os.homedir(), '.hen', 'projects');
}

async function compileTsFile(inputPath: string): Promise<string> {
  const tempJsPath = inputPath.replace(/\.ts$/, '.temp.js');
  
  await esbuild.build({
    entryPoints: [inputPath],
    bundle: true,
    platform: 'node',
    target: 'node18',
    outfile: tempJsPath,
    format: 'esm',
    external: ['commander', '@clack/prompts'],
  });
  
  return tempJsPath;
}

async function createProjectStructure(
  jsFilePath: string,
  projectPath: string,
  projectName: string
): Promise<void> {
  // Create project directory
  await fs.mkdir(projectPath, { recursive: true });
  
  // Copy the JS file as index.ts
  const jsContent = await fs.readFile(jsFilePath, 'utf-8');
  
  // Create index.ts that exports the CLI module
  const indexContent = `#!/usr/bin/env node
// Auto-generated by hen-pack-cli
${jsContent}

export const cliMeta = {
  key: '${projectName}',
  name: '${projectName}',
  version: '1.0.0',
  description: 'Packed CLI project',
};

export function register(program: any): void {
  // The bundled code should register commands directly
  if (typeof register === 'function' && register.name !== 'register') {
    register(program);
  }
}

export function dispose(): void {
  // Cleanup if needed
}
`;
  
  // Create package.json
  const packageJson = {
    name: `hen-${projectName}`,
    version: '1.0.0',
    description: 'Packed CLI project',
    type: 'module' as const,
    main: './dist/index.js',
    bin: {
      [projectName]: './dist/index.js',
    },
    scripts: {
      build: `esbuild src/index.ts --bundle --platform=node --format=esm --outfile=dist/index.js --banner:js="#!/usr/bin/env node" --external:commander --external:@clack/prompts --external:esbuild --external:fs --external:path --external:os`,
      dev: 'npm run build',
    },
    dependencies: {
      commander: '^12.0.0',
      '@clack/prompts': '^0.7.0',
    },
    devDependencies: {
      esbuild: '^0.19.0',
      '@types/node': '^20.0.0',
    },
  };
  
  await fs.writeFile(
    path.join(projectPath, 'package.json'),
    JSON.stringify(packageJson, null, 2),
    'utf-8'
  );
  
  // Create src directory
  const srcDir = path.join(projectPath, 'src');
  await fs.mkdir(srcDir, { recursive: true });
  
  // Move the generated code to src/index.ts
  await fs.writeFile(path.join(srcDir, 'index.ts'), indexContent, 'utf-8');
  
  // Create root index.ts as re-export entry
  const rootIndex = `export * from './src/index.js';\nexport { cliMeta, register, dispose } from './src/index.js';\n`;
  await fs.writeFile(path.join(projectPath, 'index.ts'), rootIndex, 'utf-8');
}

async function packCommand(options: PackOptions): Promise<void> {
  if (!options.name) {
    clack.log.error('必须指定包名 (-n <name>)');
    process.exit(1);
  }
  
  if (!options.input) {
    clack.log.error('必须指定入口文件 (-i <file>)');
    process.exit(1);
  }

  const spin = clack.spinner();
  spin.start('打包 CLI 项目...');
  
  try {
    const resolvedInput = path.resolve(options.input);
    
    // Check if file exists
    try {
      await fs.access(resolvedInput);
    } catch {
      spin.stop('入口文件不存在');
      process.exit(1);
    }
    
    const isTs = options.input.endsWith('.ts');
    let jsFilePath: string;
    
    if (isTs) {
      spin.message('编译 TypeScript 文件...');
      jsFilePath = await compileTsFile(resolvedInput);
    } else {
      jsFilePath = resolvedInput;
    }
    
    spin.message('创建项目结构...');
    const projectsDir = options.output || (await getProjectsDir());
    const projectPath = path.join(projectsDir, options.name);
    await fs.mkdir(projectsDir, { recursive: true });
    await createProjectStructure(jsFilePath, projectPath, options.name);
    
    // Cleanup temp file
    if (isTs && jsFilePath.endsWith('.temp.js')) {
      await fs.unlink(jsFilePath).catch(() => {});
    }
    
    spin.stop(`项目已打包到: ${projectPath}`);
    clack.log.success(`包名: ${options.name}`);
    clack.outro(`使用 "hen add ${projectPath}" 安装项目`);
  } catch (error) {
    spin.stop(`打包失败: ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}

async function main(): Promise<void> {
  const program = new Command();
  
  program
    .name('pack-cli')
    .description('将 TS/JS 文件打包成 Hen CLI 项目')
    .version('1.0.0');
  
  program
    .command('pack')
    .description('打包一个 TS/JS 文件为 CLI 项目')
    .requiredOption('-n, --name <name>', '包名/调用名/生成的文件夹名')
    .requiredOption('-i, --input <file>', '需要打包的文件入口 (xxx.ts/xxx.js)')
    .option('-o, --output <dir>', '输出目录 (默认: ~/.hen/projects)')
    .action(packCommand);
  
  await program.parseAsync(process.argv);
  
  if (!process.argv.slice(2).length) {
    program.help();
  }
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
